package com.ryanluo.prefloppal.models

import com.ryanluo.prefloppal.utils.Range

object Nine_Max_FacingThreeBetRanges {

    val RANGES = mapOf(

        "UTG" to mapOf(
            "UTG+1" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99",
                    "AQs", "AJs",
                    "KQs",
                    "QJs",
                    "JTs")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("ATs",
                    "AQo"))
            ),
            "UTG+2" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88",
                    "AQs", "AJs",
                    "KQs",
                    "QJs",
                    "JTs")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("ATs", "A9s",
                    "AQo"))
            ),
            "LJ" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88",
                    "AQs", "AJs",
                    "KQs",
                    "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("ATs", "A9s",
                    "AQo"))
            ),
            "HJ" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77",
                    "AQs", "AJs",
                    "KQs", "KJs",
                    "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("ATs", "A9s", "A5s",
                    "AQo"))
            ),
            "CO" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s",
                    "KTs",
                    "QTs",
                    "98s"))
            ),
            "BTN" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s",
                    "KTs",
                    "QTs",
                    "98s"))
            ),
            "SB" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s",
                    "KTs",
                    "QTs",
                    "98s"))
            ),
            "BB" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s",
                    "KTs",
                    "QTs",
                    "98s"))
            )
        ),
        "UTG+1" to mapOf(
            "UTG+2" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77",
                    "AQs", "AJs",
                    "KQs", "KJs",
                    "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("ATs", "A9s", "A5s",
                    "AQo",
                    "AJo"))
            ),
            "LJ" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s", "A4s",
                    "KTs",
                    "QTs",
                    "AJo"))
            ),
            "HJ" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s", "A4s",
                    "KTs",
                    "KQo", "QTs",
                    "AJo"))
            ),
            "CO" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s", "A4s",
                    "KTs",
                    "KQo", "QTs",
                    "AJo"))
            ),
            "BTN" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "AJo", "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s", "A4s",
                    "KTs",
                    "KQo", "QTs",
                    "J9s",
                    "ATo"))
            ),
            "SB" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs", "KTs",
                    "AQo", "QJs", "QTs",
                    "AJo", "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s",
                    "K9s",
                    "KQo",
                    "J9s",
                    "ATo"))
            ),
            "BB" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs", "KTs",
                    "AQo", "QJs", "QTs",
                    "AJo", "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs", "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s",
                    "K9s",
                    "KQo",
                    "J9s",
                    "ATo"))
            )
        ),
        "UTG+2" to mapOf(
            "LJ" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s",
                    "98s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs",
                    "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s", "A4s", "A3s", "A2s",
                    "KQo",
                    "AJo"))
            ),
            "HJ" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77", "66",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs",
                    "AQo", "QJs",
                    "JTs",
                    "T9s",
                    "98s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs",
                    "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A5s", "A4s", "A3s", "A2s",
                    "KQo",
                    "AJo",
                    "87s"))
            ),
            "CO" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77", "66", "55",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs", "KTs",
                    "AQo", "QJs", "QTs",
                    "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs",
                    "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s", "A3s", "A2s",
                    "KQo",
                    "AJo"))

            ),
            "BTN" to FacingThreeBetRange(
                callRange = Range(setOf("QQ", "JJ", "TT", "99", "88", "77", "66", "55",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs", "KTs",
                    "AQo", "QJs", "QTs",
                    "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK",
                    "AKs",
                    "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s", "A3s", "A2s",
                    "KQo",
                    "AJo"))
            ),
            "SB" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77", "66", "55",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs", "KTs",
                    "AQo", "QJs", "QTs",
                    "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs",
                    "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s", "A3s", "A2s",
                    "KQo",
                    "AJo"))
            ),
            "BB" to FacingThreeBetRange(
                callRange = Range(setOf("JJ", "TT", "99", "88", "77", "66", "55",
                    "AQs", "AJs", "ATs",
                    "KQs", "KJs", "KTs",
                    "AQo", "QJs", "QTs",
                    "JTs",
                    "T9s",
                    "98s",
                    "87s")),
                fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                    "AKs",
                    "AKo")),
                fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s", "A3s", "A2s",
                    "KQo",
                    "AJo"))

            ),
        ),
            "LJ" to mapOf(
                "HJ" to FacingThreeBetRange(
                    callRange = Range(setOf("JJ", "TT", "99", "88", "77",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs",
                        "AQo", "QJs", "QTs",
                        "JTs",
                        "T9s",
                        "98s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s", "A3s", "A2s",
                        "KQo",
                        "AJo"))
                ),
                "CO" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs",
                        "AQo", "QJs", "QTs",
                        "JTs",
                        "T9s",
                        "98s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A5s", "A4s", "A3s", "A2s",
                        "KQo",
                        "AJo",
                        "87s"))
                ),
                "BTN" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs",
                        "AQo", "QJs", "QTs",
                        "JTs",
                        "T9s",
                        "98s",
                        "87s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A5s", "A4s", "A3s", "A2s",
                        "KQo",
                        "AJo",
                        "76s"))
                ),
                "SB" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs",
                        "AQo", "KQo", "QJs", "QTs",
                        "AJo", "JTs", "J9s",
                        "T9s",
                        "98s",
                        "87s",
                        "76s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo"))
                ),
                "BB" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs",
                        "AQo", "QJs", "QTs",
                        "JTs",
                        "T9s",
                        "98s",
                        "87s",
                        "76s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KQo",
                        "AJo"))
                )
            ),
            "HJ" to mapOf(
                "CO" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs", "K9s",
                        "AQo", "KQo", "QJs", "QTs", "Q9s",
                        "AJo", "JTs", "J9s",
                        "T9s",
                        "98s",
                        "87s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo",
                        "76s"))
                ),
                "BTN" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs", "K9s",
                        "AQo", "KQo", "QJs", "QTs", "Q9s",
                        "AJo", "JTs", "J9s",
                        "T9s",
                        "98s",
                        "87s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo",
                        "76s",
                        "65s",
                        "54s"))
                ),
                "SB" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs", "K9s",
                        "AQo", "KQo", "QJs", "QTs", "Q9s",
                        "AJo", "JTs", "J9s",
                        "T9s",
                        "98s",
                        "87s",
                        "76s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo"))
                ),
                "BB" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs",
                        "KQs", "KJs", "KTs",
                        "AQo", "QJs", "QTs",
                        "JTs",
                        "T9s",
                        "98s",
                        "87s",
                        "76s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KQo",
                        "AJo"))
                )
            ),
            "CO" to mapOf(
                "BTN" to FacingThreeBetRange(
                    callRange = Range(setOf("99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs", "A9s", "A5s",
                        "KQs", "KJs", "KTs", "K9s",
                        "AQo", "KQo", "QJs", "QTs", "Q9s",
                        "JTs", "J9s",
                        "T9s", "T8s",
                        "98s",
                        "87s",
                        "76s",
                        "65s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ", "TT",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A8s", "A7s", "A6s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo",
                        "97s",
                        "86s",
                        "75s",
                        "54"))
                ),
                "SB" to FacingThreeBetRange(
                    callRange = Range(setOf("99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs", "A9s", "A5s",
                        "KQs", "KJs", "KTs", "K9s",
                        "AQo", "KQo", "QJs", "QTs", "Q9s",
                        "JTs", "J9s",
                        "T9s", "T8s",
                        "98s",
                        "87s",
                        "76s",
                        "65s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ", "TT",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A8s", "A7s", "A6s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo",
                        "97s",
                        "86s",
                        "75s",
                        "54"))
                ),
                "BB" to FacingThreeBetRange(
                    callRange = Range(setOf("99", "88", "77", "66", "55", "44",
                        "AQs", "AJs", "ATs", "A9s", "A5s",
                        "KQs", "KJs", "KTs", "K9s",
                        "AQo", "KQo", "QJs", "QTs", "Q9s",
                        "AJo", "JTs", "J9s",
                        "T9s",
                        "98s",
                        "87s",
                        "76s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ", "TT",
                        "AKs",
                        "AKo")),
                    fourBetBluffRange = Range(setOf("A8s", "A4s", "A3s", "A2s",
                        "KJo",
                        "ATo", "T8s",
                        "97s",
                        "65s",
                        "54"))
                )
            ),
            "BTN" to mapOf(
                "SB" to FacingThreeBetRange(
                    callRange = Range(setOf("88", "77", "66", "55", "44", "33", "22",
                        "ATs", "A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KQs", "KJs", "KTs", "K9s", "K8s", "K7s",
                        "KQo", "QJs", "QTs", "Q9s", "Q8s",
                        "AJo", "KJo", "QJo", "JTs", "J9s", "J8s",
                        "ATo", "KTo", "T9s", "T8s", "T7s",
                        "98s", "97s",
                        "87s",
                        "76s",
                        "65s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ", "TT", "99",
                        "AKs", "AQs", "AJs",
                        "AKo",
                        "AQo")),
                    fourBetBluffRange = Range(setOf("K6s", "K5s", "K4s",
                        "Q7s",
                        "J7s",
                        "QTo", "JTo",
                        "K9o",
                        "A8o", "86s",
                        "75s",
                        "64s",
                        "A5o", "54s",
                        "A4o", "43s",
                        "A3o"))
                ),
                "BB" to FacingThreeBetRange(
                    callRange = Range(setOf("88", "77", "66", "55", "44", "33", "22",
                        "ATs", "A9s", "A8s", "A7s", "A6s", "A5s", "A4s", "A3s", "A2s",
                        "KQs", "KJs", "KTs", "K9s", "K8s", "K7s",
                        "KQo", "QJs", "QTs", "Q9s", "Q8s",
                        "AJo", "KJo", "QJo", "JTs", "J9s", "J8s",
                        "ATo", "KTo", "T9s", "T8s", "T7s",
                        "98s", "97s",
                        "87s",
                        "76s",
                        "65s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ", "TT", "99",
                        "AKs", "AQs", "AJs",
                        "AKo",
                        "AQo")),
                    fourBetBluffRange = Range(setOf("K6s", "K5s", "K4s",
                        "Q7s",
                        "J7s",
                        "QTo", "JTo",
                        "K9o",
                        "A8o", "86s",
                        "75s",
                        "64s",
                        "A5o", "54s",
                        "A4o", "43s",
                        "A3o"))
                )
            ),
            "SB" to mapOf(
                //missing other sb mappings for now

                "BB" to FacingThreeBetRange(
                    callRange = Range(setOf("TT", "99", "88",
                        "ATs",
                        "KQs", "KJs",
                        "KQo", "QJs",
                        "AJo", "KJo",
                        "ATo",
                        "95s",
                        "85s",
                        "74s",
                        "43s")),
                    fourBetValueRange = Range(setOf("AA", "KK", "QQ", "JJ",
                        "AKs", "AQs", "AJs",
                        "AKo",
                        "AQo")),
                    fourBetBluffRange = Range(setOf("J4s",
                        "Q5o",
                        "Q4o",
                        "K3o",
                        "K2o"))
                )
            )

    )
}